---
- name: Install KVM on Ubuntu host
  hosts: ubuntu
  become: yes
  tasks:
    - name: Install KVM and related packages on Ubuntu
      apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
        state: present
      when: ansible_os_family == "Debian"

    - include: vm-playbook.yaml