---
- name: Create a VM on KVM host
  hosts: ubuntu
  become: yes
  tasks:
    - name: Create a VM for nginx
      virt:
        name: nginx_webserver
        state: running
        xml: "{{ lookup('file', 'ubuntu.xml' }}"